<?php
/**
 * @file
 * Install file for AdminRSS.
 *
 * @since DRUPAL-5
 * @license General Public License version 2.0 and later
 */

use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function adminrss_install() {
  $message = t('AdminRSS has been installed and now needs to be <a href=":link" title="AdminRSS Configuration">configured</a>.', [
    ':link' => Url::fromRoute(\Drupal\adminrss\AdminRss::ROUTE_SETTINGS)->toString(),
  ]);
  drupal_set_message($message, 'status');
}
