<?php
/**
 * @file
 * Constant definitions for AdminRSS
 *
 * @since DRUPAL-5
 * @license General Public License version 2.0 and later
 */

// Configuration variables.
const ADMINRSS_VAR_KEY       = 'adminrss_key';
const ADMINRSS_VAR_LINK_TYPE = 'adminrss_link_type';

// Options for ADMINRSS_VAR_LINK_TYPE.
const ADMINRSS_LINK_QUEUE = 0;
const ADMINRSS_LINK_EDIT  = 1;

// Menu paths.
const ADMINRSS_PATH_HOME     = 'adminrss';
const ADMINRSS_PATH_SETTINGS = 'admin/config/adminrss';
