<?php
/**
 * @file
 * Constant definitions for AdminRSS
 *
 * @since DRUPAL-5
 * @license General Public License version 2.0 and later
 */

/**
 * Configuration variables
 */
define('ADMINRSS_VAR_KEY',       'adminrss_key');
define('ADMINRSS_VAR_LINK_TYPE', 'adminrss_link_type');

/**
 * Menu paths
 */
define('ADMINRSS_PATH_HOME',     'adminrss');
define('ADMINRSS_PATH_SETTINGS', 'admin/settings/adminrss');
